### ISSUE TITLE
Max number of yaml aliases is not configurable

### ISSUE THREAD

**Issue by r-glyde** [sky-uk/kafka-configurator#52]
We use yaml anchors and aliases to reduce duplication for some of our topic configurations. Following #51 this is now broken in a project that is creating lots of topics due to an update in snakeyaml that sets a maximum number of allowed aliases. We see the error below:

```ERROR com.sky.kafka.configurator.Main$ - Number of aliases for non-scalar nodes exceeds the specified max=50```

Example configuration:

```yaml
test-topic: &DEFAULT
  partitions: 9
  replication: 3
  config:
    cleanup.policy: compact

topic-one: *DEFAULT
topic-two: *DEFAULT
topic-three: *DEFAULT
# Repeats > 50 times
```

This is configurable in snakeyaml but circe-yaml does not currently give you this option - see circe/circe-yaml#136.

For now we should probably revert the circe update and wait for the linked issue to be resolved.
